/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoVarejo.View;

import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import projetoVarejo.DAO.ProdutoDAO;
import projetoVarejo.OBJECTS.Fornecedor;
import projetoVarejo.OBJECTS.Produto;

/**
 *
 * @author Deyvid Yancey
 */
public class ProdutoCompra1 extends javax.swing.JFrame {
JTextField descricaoDaPrincipaL1;
JTextField descricaoDaPrincipaL2;
JTextField descricaoDaPrincipaL3;
JTextField descricaoDaPrincipaL4;
JTextField descricaoDaPrincipaL5;

    /**
     * Creates new form ProdutoCompra1
     */
    public ProdutoCompra1(JTextField descricao1,JTextField descricao2,JTextField descricao3,JTextField descricao4,JTextField descricao5) {
        initComponents();
        listar();
        this.descricaoDaPrincipaL1=descricao1;
        this.descricaoDaPrincipaL2=descricao2;
        this.descricaoDaPrincipaL3=descricao3;
        this.descricaoDaPrincipaL4=descricao4;
        this.descricaoDaPrincipaL5=descricao5;
      
    }

    ProdutoCompra1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ftPRECODECOMPRA = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfESTOQUE = new javax.swing.JTextField();
        tfPRECODEVENDA = new javax.swing.JTextField();
        tfUNIDADE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfPORCENTAGEM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbTIPO = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tfFORNECEDOR = new javax.swing.JTextField();
        btCONFIRMAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu de Compra");

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço de compra", "Preço de venda", "Estoque", "Fornecedor", "Quantidade", "Porcentagem de lucro", "Tipo"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Nome");

        jLabel3.setText("Preço de compra");

        jLabel4.setText("Preço de Venda");

        jLabel5.setText("Fornecedor");

        tfCodigo.setEditable(false);
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        jLabel10.setText("Código");

        ftPRECODECOMPRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftPRECODECOMPRAKeyPressed(evt);
            }
        });

        jLabel6.setText("Estoque");

        tfPRECODEVENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPRECODEVENDAActionPerformed(evt);
            }
        });
        tfPRECODEVENDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPRECODEVENDAKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPRECODEVENDAKeyReleased(evt);
            }
        });

        tfUNIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUNIDADEActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade");

        tfPORCENTAGEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPORCENTAGEMActionPerformed(evt);
            }
        });
        tfPORCENTAGEM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPORCENTAGEMKeyPressed(evt);
            }
        });

        jLabel8.setText("Porcentagem de lucro");

        cbTIPO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Unidade", "Grama", "Kilo", "Tonelada", "Ml", "Litro", "Metro", "Centimetros", "Unidade", "Metro Cúbico" }));

        jLabel9.setText("Tipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(ftPRECODECOMPRA, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(tfESTOQUE))
                            .addComponent(jLabel7)
                            .addComponent(tfUNIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFORNECEDOR)
                            .addComponent(tfPRECODEVENDA)
                            .addComponent(tfPORCENTAGEM)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(0, 81, Short.MAX_VALUE)))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftPRECODECOMPRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPORCENTAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfESTOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUNIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPRECODEVENDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        btCONFIRMAR.setText("Confirmar Pedido");
        btCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCONFIRMARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("BEM VINDO AO MENU DE COMPRA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btCONFIRMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(btCONFIRMAR, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        Fornecedor f = new Fornecedor();
        //jTabbedPane1.setSelectedIndex(0);
        tfCodigo.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0).toString());
        tfNome.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1).toString());
        ftPRECODECOMPRA.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2).toString());
        tfPRECODEVENDA.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 3).toString());
        tfESTOQUE.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 4).toString());
        tfFORNECEDOR.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 5).toString());
        tfUNIDADE.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 6).toString());
        tfPORCENTAGEM.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 7).toString());
        cbTIPO.setSelectedItem(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 8).toString());

    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void ftPRECODECOMPRAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftPRECODECOMPRAKeyPressed
        /* ProdutoDAO dao = new ProdutoDAO();
        double valorDeCompra,porcentagem;
        valorDeCompra= Double.parseDouble(ftPRECODECOMPRA.getText());
        porcentagem=
        dao.valorDeVenda(valorDeCompra, PROPERTIES);*/
    }//GEN-LAST:event_ftPRECODECOMPRAKeyPressed

    private void tfPRECODEVENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPRECODEVENDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPRECODEVENDAActionPerformed

    private void tfPRECODEVENDAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPRECODEVENDAKeyPressed

    }//GEN-LAST:event_tfPRECODEVENDAKeyPressed

    private void tfPRECODEVENDAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPRECODEVENDAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPRECODEVENDAKeyReleased

    private void tfUNIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUNIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUNIDADEActionPerformed

    private void tfPORCENTAGEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPORCENTAGEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPORCENTAGEMActionPerformed

    private void tfPORCENTAGEMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPORCENTAGEMKeyPressed

    }//GEN-LAST:event_tfPORCENTAGEMKeyPressed

    private void btCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCONFIRMARActionPerformed
        /*frmComercio desktop = new frmComercio();
        cp = new ConfirmaProduto();

        cp.receber(tfCodigo.getText(), tfESTOQUE.getText(), tfNome.getText(), tfPRECODEVENDA.getText(), tfUNIDADE.getText());
        desktop.add(cp);
        cp.show();*/
        /*int codfornecedor;

        obj.setNome(tfNome.getText());
        obj.setPrecoDeCompra(Double.parseDouble(ftPRECODECOMPRA.getText()));
        obj.setPrecoDeVenda(Double.parseDouble(tfPRECODEVENDA.getText()));
        obj.setEstoque(tfESTOQUE.getText());
        //    codfornecedor = id_fornecedor.get(tfFORNECEDOR.getText());
        //obj.setFornecedor(codfornecedor);
        obj.setUnidade(tfUNIDADE.getText());
        obj.setPorcentagem(Double.parseDouble(tfPORCENTAGEM.getText()));
        obj.setTipo( cbTIPO.getSelectedItem().toString());

        // cp.receber(tfCodigo.getText(), tfESTOQUE.getText(), tfNome.getText(), tfPRECODEVENDA.getText(), tfUNIDADE.getText());

        */

        /* if (tfNome.getText().isEmpty()) {

            if (cp==null) {
                cp = new ConfirmaProduto();
                cp.setLocale(null);
                cp.setVisible(true);
                cp.setResizable(false);
            }else{
                cp.setLocale(null);
                cp.setVisible(true);
                cp.setResizable(false);
            }
            //cp.enviapalava(this,tfNome.getText());
        }*/
       // ConfirmaProduto cp = new ConfirmaProduto(this.tfNome);
this.descricaoDaPrincipaL1.setText(this.tfNome.getText());
this.descricaoDaPrincipaL2.setText(this.tfCodigo.getText());
this.descricaoDaPrincipaL3.setText(this.tfPRECODEVENDA.getText());
this.descricaoDaPrincipaL4.setText(this.tfUNIDADE.getText());
this.descricaoDaPrincipaL5.setText(this.tfPRECODEVENDA.getText());





    }//GEN-LAST:event_btCONFIRMARActionPerformed

     public void listar() {
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.listarProduto();
        DefaultTableModel dados = (DefaultTableModel) tabelaProduto.getModel();
        dados.setNumRows(0);
        for (Produto c : lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getPrecoDeCompra(),
                c.getPrecoDeVenda(),
                c.getEstoque(),
                c.getFornecedor(),
                c.getUnidade(),
                c.getPorcentagem(),
                c.getTipo()
            });

        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoCompra1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoCompra1().setVisible(true);
               //new ProdutoCompra1(tfCodigo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCONFIRMAR;
    private javax.swing.JComboBox<String> cbTIPO;
    private javax.swing.JFormattedTextField ftPRECODECOMPRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfESTOQUE;
    private javax.swing.JTextField tfFORNECEDOR;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPORCENTAGEM;
    private javax.swing.JTextField tfPRECODEVENDA;
    private javax.swing.JTextField tfUNIDADE;
    // End of variables declaration//GEN-END:variables
}
